### ISSUE TITLE
错误: cannot open resource

### ISSUE THREAD

**Issue by qwe3107231** [jiluoQAQ/pokemon_whois#1]
用的go-cqhttpv1.0.1
Hoishinoibot
win10
插件放到modules，bot已添加插件名称
发送 关键词提示
错误:
[Errno 2] No such file or directory: 'C:\\Users\\Administrator\\HoshinoBot\\hoshino\\modules\\pokemon_whois\\icon\\小山猪.png'
手动解压icon压缩包后提示
错误:
cannot open resource
hoshinobot后台无报错

**Comment by duoshoumiao** [comment]
我这边是错误:
[Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\HoshinoBot-master - 副本\\HoshinoBot-master\\hoshino\\modules\\pokemon_whois\\fonts\\sakura.ttf'

**Comment by duoshoumiao** [comment]
删掉副本2个字后和上面那位一样了

**Comment by duoshoumiao** [comment]
> 用的go-cqhttpv1.0.1 Hoishinoibot win10 插件放到modules，bot已添加插件名称 发送 关键词提示 错误: [Errno 2] No such file or directory: 'C:\Users\Administrator\HoshinoBot\hoshino\modules\pokemon_whois\icon\小山猪.png' 手动解压icon压缩包后提示 错误: cannot open resource hoshinobot后台无报错

![image](https://github.com/jiluoQAQ/pokemon_whois/assets/94856184/63f36526-031e-4cea-9b37-0aa1def7e251)
这里多了个S。删了就好

**Comment by jiluoQAQ** [comment]
很早写的，网页直接拉上去的，文件夹名字写错了，已经改好了
